apiVersion: v1
kind: ConfigMap
metadata:
    name: mosquitto-config-file
data:
    # filename ðŸ‘‡
    mosquitto.conf: |
        # file contents ðŸ‘‡
        log_dest stdout
        log_type all
        log_timestamp true
        listener 9001